# Generated by Django 2.0 on 2018-10-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20181021_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
