# Generated by Django 2.0 on 2018-08-02 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='member',
        ),
        migrations.AddField(
            model_name='meeting',
            name='venue',
            field=models.TextField(default='SJT'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
